# install openjdk 11

---

- name: install openjdk for ubuntu
  apt:
    name: openjdk-11-jre-headless
  when: dist == "ubuntu"

- name: install openjdk for centos
  yum:
    name: java-11-openjdk-headless
  when: dist == "centos"
