# install nginx

---

- name: install nginx for ubuntu
  apt:
    name: nginx
  when: dist == "ubuntu"

- name: create www-data user for centos
  user:
    name: www-data
    shell: /usr/sbin/nologin
  when: dist == "centos"

- name: install epel-release for centos
  yum:
    name: epel-release
  when: dist == "centos"

- name: install nginx for centos
  yum:
    name: nginx
  when: dist == "centos"
