#
# Define ALL deploy hosts grouped by 'itranswarp'.
#

all:
  children:
    itranswarp:
      hosts:
        # internal IP list:
        172.16.0.120:
        172.16.0.121:

#
# NOTE: if you want to deploy via bastion server, add ssh config to ~/.ssh/config:
#
# Host 172.16.0.120
#   User ubuntu
#   ProxyCommand ssh -W %h:%p bastion.server.name
#
