# reload supervisor conf and restart service

---

- name: start supervisor if not running for ubuntu
  service:
    name: supervisor
    state: started
  when: dist == "ubuntu"

- name: start supervisor if not running for centos
  service:
    name: supervisord
    state: started
  when: dist == "centos"

- name: start service itranswarp
  supervisorctl:
    name: itranswarp
    state: restarted # restarted = supervisorctl update && supervisorctl restart
