# generate nginx conf

---

- name: init nginx cache dir /var/cache/nginx/itranswarp
  file:
    path: /var/cache/nginx/itranswarp
    state: directory
    owner: www-data
    group: www-data

- name: init nginx tmp dir /var/cache/nginx/tmp
  file:
    path: /var/cache/nginx/tmp
    state: directory
    owner: www-data
    group: www-data

- name: disable default conf for ubuntu
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: dist == "ubuntu"

- name: disable default conf for centos
  file:
    path: /etc/nginx/conf.d/default
    state: absent
  when: dist == "centos"

- name: generate nginx conf for itranswarp
  template:
    src: templates/nginx.j2
    dest: /srv/itranswarp-{{ timestamp }}/nginx.conf

- name: make symbol link for ubuntu
  file:
    src: /srv/itranswarp-{{ timestamp }}/nginx.conf
    dest: /etc/nginx/sites-enabled/itranswarp.conf
    state: link
    force: yes
  when: dist == "ubuntu"

- name: make symbol link for centos
  file:
    src: /srv/itranswarp-{{ timestamp }}/nginx.conf
    dest: /etc/nginx/conf.d/itranswarp.conf
    state: link
    force: yes
  when: dist == "centos"

- name: copy ssl certs
  copy:
    src: environments/{{ profile }}/ssl
    dest: /srv/itranswarp-{{ timestamp }}/
